# -*- coding: utf-8 -*-
"""Regenerate CLAUDE.md from constitution/total.md + constitution/agent.<role>.md.

Source of truth:
  constitution/total.md         — universal constitution, synced from agent-core
                                  to all clones via sync_infra.py
  constitution/agent.<role>.md  — this clone's agent-specific articles
                                  (per-role file, owned by that agent only)
  .role                         — single-line file at repo root with this
                                  clone's role string (`core`, `rules`,
                                  `trade`, `data`, `research`); not git-tracked
                                  (.gitignore'd); per-clone setup

Generated:
  CLAUDE.md  — banner + total.md content + agent.<role>.md content.
               DO NOT edit directly; pre-commit hook blocks it.

Role detection precedence:
  1. `.role` file at repo root (canonical)
  2. Fall back to clone directory basename (`agent-<role>`)
  3. If neither works, blocking error (exit 1)

Backward-compat during migration (Phase 1-3):
  - if `agent.<role>.md` doesn't exist but legacy `agent.md` does, use legacy
    with a stderr warning citing the migration proposal.

Usage:
  python tools/regen_constitution.py              # regenerate CLAUDE.md
  python tools/regen_constitution.py --check      # exit 1 if stale, else 0
  python tools/regen_constitution.py --root PATH  # target a specific repo

Per proposal proposals/per_role_agent_md_files.md.
"""
import argparse
import sys
from pathlib import Path

BANNER = (
    "<!-- AUTO-GENERATED by tools/regen_constitution.py — DO NOT EDIT DIRECTLY -->\n"
    "<!-- Sources: constitution/total.md (synced from agent-core) + constitution/agent.<role>.md (this clone, per role) -->\n"
    "<!-- Regen command: python tools/regen_constitution.py -->\n"
    "\n"
)

AGENT_SECTION_HEADER = (
    "---\n"
    "\n"
    "# Agent-Specific 条款\n"
    "\n"
    "以下条款由本 agent 的 `constitution/agent.md` 定义，是对总宪法的补充，"
    "不得放宽总宪法约束（见第十三条）。\n"
    "\n"
)


def detect_role(root: Path) -> str:
    """Detect this clone's role.

    Order:
      1. Read `.role` file at repo root (canonical).
      2. Fall back to clone directory basename matching `agent-<role>`.
      3. If neither works, exit 1 with a recovery hint.

    The `.role` file is per-clone (in .gitignore) and the canonical source.
    Directory-name fallback is for transition convenience only and writes a
    stderr warning so the operator knows to set up `.role`.
    """
    role_file = root / ".role"
    if role_file.is_file():
        role = role_file.read_text(encoding="utf-8").strip()
        if role:
            return role

    dirname = root.name.lower()
    if dirname.startswith("agent-"):
        guessed = dirname[6:]
        print(
            f"[WARN] {root.name}: .role file missing or empty; using clone "
            f"directory name fallback ('{guessed}'). "
            f"Fix: echo {guessed} > {role_file}",
            file=sys.stderr,
        )
        return guessed

    # P-0059 Phase 2.3c: derive agent enum from .governance/config.json if available
    agent_hint = "<core|...>"
    try:
        import json
        cfg_path = root / ".governance" / "config.json"
        if cfg_path.exists():
            cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
            names = [a["name"] for a in cfg.get("agents", [])]
            if names:
                agent_hint = "<" + "|".join(names) + ">"
    except Exception:
        pass  # fallback to hardcoded hint

    print(
        f"[ERROR] Cannot detect role for {root}.\n"
        f"  .role file missing or empty: {role_file}\n"
        f"  Directory name '{dirname}' does not start with 'agent-'.\n"
        f"  Fix: echo {agent_hint} > {role_file}",
        file=sys.stderr,
    )
    sys.exit(1)


def resolve_agent_path(root: Path, role: str) -> Path:
    """Resolve agent-specific constitution file path.

    Prefers per-role file `constitution/agent.<role>.md`. Falls back to
    legacy `constitution/agent.md` with stderr warning during transition
    (proposal `per_role_agent_md_files.md` Phases 1-3).

    Returns the path that exists; if neither exists returns the per-role
    path (caller will see missing-file when reading).
    """
    per_role = root / "constitution" / f"agent.{role}.md"
    if per_role.is_file():
        return per_role

    legacy = root / "constitution" / "agent.md"
    if legacy.is_file():
        print(
            f"[WARN] Using legacy {legacy.name} instead of {per_role.name}.\n"
            f"  Migration to per-role files is incomplete; see "
            f"proposals/per_role_agent_md_files.md Phase 3.",
            file=sys.stderr,
        )
        return legacy

    return per_role


def build_constitution(total_path: Path, agent_path: Path) -> str:
    """Assemble CLAUDE.md content from source files.

    Returns:
        Full generated content including banner, total, and (if non-empty)
        agent-specific section.
    """
    total = total_path.read_text(encoding="utf-8").rstrip() + "\n"
    agent = (
        agent_path.read_text(encoding="utf-8").strip() if agent_path.exists() else ""
    )

    out = [BANNER, total]
    if agent:
        out.append("\n")
        out.append(AGENT_SECTION_HEADER)
        out.append(agent + "\n")
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if CLAUDE.md is out of sync with sources",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Repo root to regenerate (default: current working dir)",
    )
    args = parser.parse_args()

    root: Path = args.root.resolve()
    role = detect_role(root)
    total = root / "constitution" / "total.md"
    agent = resolve_agent_path(root, role)
    output = root / "CLAUDE.md"

    if not total.is_file():
        print(f"[ERROR] Missing {total}", file=sys.stderr)
        return 2

    generated = build_constitution(total, agent)

    if args.check:
        current = output.read_text(encoding="utf-8") if output.is_file() else ""
        if current == generated:
            print(f"[OK] {output} in sync with constitution/*.md")
            return 0
        print(
            f"[STALE] {output} is out of sync with constitution/*.md. "
            "Run: python tools/regen_constitution.py",
            file=sys.stderr,
        )
        return 1

    output.write_text(generated, encoding="utf-8")
    print(f"[OK] Regenerated {output} ({len(generated)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
